### ISSUE TITLE
Hartigan dip test generally looks very close to 1 likely due to outliers

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytominergallery#13]
vignettes/feature_distribution_analysis.Rmd

**Comment by shntnu** [comment]
From EG: The Hartigan dip test generally looks very close to 1 and in its adjusted form is nearly always 1. I suspect that this too, is very sensitive to outliers. Unimodality testing is as hard as normality testing, I fear, and a robust test of unimodality would be something of a contradiction in terms.

**Comment by mrohban** [comment]
Obviously outliers would not make a multimodal distribution look unimodal in the dip test (actually it's more likely for the reverse to happen). Furthermore, eyeballing the density of the features shows that the test prediction matches the reality almost all the time.

**Comment by shntnu** [comment]
#26
