### ISSUE TITLE
install fails  

### ISSUE THREAD

**Issue by cells2numbers** [cytomining/cytominergallery#15]
installation in R 3.3.2 using  

devtools::install_github("cytomining/cytominergallery", dependencies = TRUE, build_vignettes = TRUE)

fails with the following error log. 

Error: processing vignette 'single_cell_analysis.Rmd' failed with diagnostics:
Path does not exist and create = FALSE
In addition: Warning message:
In tools::buildVignettes(dir = ".", tangle = TRUE) :
  Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/feature_distribution_analysis.Rmd’
(Is a VignetteBuilder field missing?)
Execution halted
Error: Command failed (1)

Comment from Shantanu:

Ah that was because we didn't intend for that to be a vignette but
rather a notebook, but somehow overlooked the fact that
install.packages() will try to build it.

**Comment by shntnu** [comment]
#20
