### ISSUE TITLE
Install fails withError: processing vignette 'single_cell_analysis.Rmd' failed with diagnostics:

### ISSUE THREAD

**Issue by cells2numbers** [cytomining/cytominergallery#23]
Install using 
```R
devtools::install_github("cytomining/cytominergallery", dependencies = TRUE, build_vignettes = TRUE)
```
fails with 
```R
Quitting from lines 47-63 (single_cell_analysis.Rmd)
Error: processing vignette 'single_cell_analysis.Rmd' failed with diagnostics:
Path does not exist and create = FALSE
Execution halted
Error: Command failed (1)
```

**Comment by shntnu** [comment]
Did you do this?

Download this [sqlite](https://s3.amazonaws.com/imaging-platform-collaborator/2016_09_09_cytominer_workshop/ljosa_jbiomolscreen_2013.sqlite) file into `~/Downloads` (required by the vignette `single_cell_analysis`).


(from https://github.com/cytomining/cytominergallery/blob/master/README.md)

**Comment by cells2numbers** [comment]
That was it :) Accidentally deleted the download, install finishes now!
