### ISSUE TITLE
Implement Similarity network fusion

### ISSUE THREAD

**Issue by cells2numbers** [cytomining/cytominergallery#42]
cloned issue from https://github.com/cytomining/cytominer/issues/49

sources: similarity network fusion
http://www.nature.com/nmeth/journal/v11/n3/full/nmeth.2810.html

R implementation 
https://github.com/maxconway/SNFtool/blob/master/R/SNF.R

Dependencies in http://r-pkgs.had.co.nz/description.html#dependencies

**Comment by shntnu** [comment]
#43
