### ISSUE TITLE
Dataset for Nat Methods paper + code

### ISSUE THREAD

**Issue by eoziolor** [cytomining/cytominergallery#56]
Hi!

First of all than you for this wonderful set of tools. This absolutely moves the field miles ahead in ability of new people to get up and going on image analysis.

One things that I found myself needing is a way to replicate your work in the paper. The dataset you provide for training is comprised of 14K cells, rather than the one of 150K from the paper. As well there are many great visualizations you accomplish in the paper that are not shown in some of the vignettes (like heatmaps of pairwise comparisons or heatmaps of plate setup), which can be VERY useful to start with. If you could provide the workflow from the paper with the original dataset, that would be absolutely wonderful!

Thank you!

-Elias

**Comment by shntnu** [comment]
@eoziolor excited to have you volunteer to create this vignette! I'll create a branch with this issue. Let's use that to track this

**Comment by shntnu** [comment]
From this paper https://www.nature.com/articles/nmeth.4397, we want to reproduce Figure 3, 4a, 6

Fig 3
![image](https://media.nature.com/m685/nature-assets/nmeth/journal/v14/n9/images/nmeth.4397-F3.jpg)

Fig 4
![image](https://media.nature.com/m685/nature-assets/nmeth/journal/v14/n9/images/nmeth.4397-F4.jpg)

Fig 6
![image](https://media.nature.com/m685/nature-assets/nmeth/journal/v14/n9/images/nmeth.4397-F6.jpg)

**Comment by eoziolor** [comment]
Shantanu,
Thanks for getting the data and code to me for Figure 3. When you get the chance, if you have some of the code to help me through the rest of the analysis, that would be wonderful. Thanks again.
-Elias

**Comment by shntnu** [comment]
Figure 5 was generated using a different dataset, not BBBC021. 

I propose you skip that and work on Fig 6 instead

here are the packages / functions you will need
6a - `heatmap.2::heatmap.2` on the treatment profiles 
6b - `stats::prcomp` on single cell data, subsampled
6c - `tsne::tsne` on single cell data, subsampled
6d - `spade` package on single cell data, subsampled

**Comment by shntnu** [comment]
@eoziolor Feel free to reopen if you revisit this
