### ISSUE TITLE
Report correlations between features

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytominergallery#9]
vignettes/feature_distribution_analysis.Rmd

**Comment by shntnu** [comment]
As for the feature correlation, the main problem is numerical: when very large vectors are compared the floating point arithmetic saturates at one point, when very small values are added to a large cumulated one. For one of the datasets, I used the following algorithm (original paper attached):
https://www.wikiwand.com/en/Algorithms_for_calculating_variance#/Parallel_algorithm

Paper: https://paperpile.com/shared/J1QFrv

**Comment by mrohban** [comment]
I am using `cor` function in R. Doesn't it take care of these numerical imprecisions?
